#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: ruby

rvm:
    - 2.1.0

sudo: false

install:
    - gem install json

script:
    - ruby bin/concat-test-json.rb grid/data/*/*/test.json >/tmp/tests.json
    - diff -u grid/data/tests.json /tmp/tests.json

