#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at travis-ci.org
#
#-----------------------------------------------------------------------------

language: cpp

sudo: false

install:
    - gem install json

script:
    - bin/concat-test-json.rb data/grid/data/*/*/test.json >/tmp/tests.json
    - diff -u grid/data/tests.json /tmp/tests.json

